### ISSUE TITLE
comma vs semicolon

### ISSUE THREAD

**Issue by Eomm** [fastify/workflows#58]
The workflow input option has 2 options that accept a string with a comma and semicolon.

I think we should be consistent and accept only one char, or both

<img width="729" alt="image" src="https://user-images.githubusercontent.com/11404065/184072408-95597d36-2c9a-407b-b0a3-c83078e3c970.png">

**Comment by Uzlopak** [comment]
The issue is, that license-check uses semicolons and dependabot automerge uses commas. If I feed license-checker with a comma separated list it says:
`Warning: As of v17 the --onlyAllow argument takes semicolons as delimeters instead of commas (some license names can contain commas)`

So it means, that we maybe have to patch our fastify/github-action-merge-dependabot to handle semicolons instead of commas

**Comment by Uzlopak** [comment]
@Fdawgs 
I guess when @simoneb merges the PR in https://github.com/fastify/github-action-merge-dependabot/pull/250 we could publish a new version?

**Comment by Fdawgs** [comment]
Sounds like a plan. I'll trigger the bot anyway just so the PR is ready to go.

**Comment by Uzlopak** [comment]
reopening, as we did not solve it yet in this repo

**Comment by Uzlopak** [comment]
@Fdawgs 

We are ready to release the kraken.
